name = "my-worker"
main = "src/index.js"
compatibility_date = "2025-12-29"


[[durable_objects.bindings]]
name = "ROOM"
class_name = "ShichinarabeRoom"

[[durable_objects.bindings]]
name = "MATCH"
class_name = "Matchmaker"

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "MyDurableObject", to = "ShichinarabeRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Matchmaker"]

[[d1_databases]]
binding = "DB"
database_name = "shitinarabe_db"
database_id = "3a448916-cd75-4fa4-87c6-733f2e6d49e6"

[assets]
directory = "./public"
