name = "my-worker"
main = "src/index.js"
compatibility_date = "2025-12-29"


[[durable_objects.bindings]]
name = "ROOM"
class_name = "ShichinarabeRoom"

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "MyDurableObject", to = "ShichinarabeRoom" }
]