name = "shichinarabe"
main = "src/index.js"
compatibility_date = "2024-11-01"

[durable_objects]
bindings = [
  { name = "ROOM", class_name = "ShichinarabeRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ShichinarabeRoom"]
